version: '2'
services:
  backend:
    build:
      context: .
      dockerfile: df.dev
    image: aws-summit-amplify:dev
    container_name: aws-summit-amplify.dev.backend
    hostname: backend
    environment:
      NODE_ENV: "development"
    volumes:
      - ".:/home/aws-summit-amplify"
    ports:
      - "3100:3000"
      - "9229:9229"
#   entrypoint: ["npm", "run", "debug_inspect"]
    entrypoint: ["tail", "-f"]
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elasticsearch.dev
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    restart: unless-stopped